### PR TITLE
Disable automatic gc

### PR DESCRIPTION
**Pull request by rayosborn**
* Enables manual garbage collection to ensure that it is conducted in the main PyQt thread. Automatic garbage collection in subsidiary threads has been known to cause application crashes.
* Fixes a bug when initializing PyQt subclasses with multiple inheritance. This is allowed in PyQt5 but not in PySide2.
* Adds an "Edit Preferences" menu item to allow the default values of NeXus parameters, such as memory limits and compression filters, to be changed. 
* Adds support for using the NeXus `interpretation` attribute to define RGB and RGBA images.
* Makes the "Manage Backups" dialog scrollable.

### CODE REVIEW

**Comment by tacaswell** [comment]
> Enables manual garbage collection to ensure that it is conducted in the main PyQt thread. Automatic garbage collection in subsidiary threads has been known to cause application crashes.

This is a bit worrying, do you have any reference (issues / mailing list / ...)?

**Comment by rayosborn** [comment]
There's an old blog post at https://pydev.blogspot.com/2014/03/should-python-garbage-collector-be.html, but I have seen similar statements elsewhere. I based my code on this post. We will do extensive testing. If we still get the occasional crash, I will let you know.

**Comment by tacaswell** [comment]
That both makes sense and is very worrying...

**Comment by rayosborn** [comment]
Anecdotally, this change does seem to have eliminated crashes in recent weeks. Before the change, it was possible to run NeXpy for several hours before such a crash, so its infrequency might be why it has not been a more widely discussed problem.

**Pull request merged**
