### PR TITLE
Mnt py3k

### PR DESCRIPTION
**Pull request by tacaswell**
First pass at python3 compatibility.  It at least starts, needs further testing.

This includes commits from #57

### CODE REVIEW

**Comment by rayosborn** [comment]
This is too far behind the master branch now, so it will be easier to issue a new pull request using many of the suggested changes here.

**Comment by tacaswell** [comment]
Rebased and re-opened.

**Comment by rayosborn** [comment]
Thanks - that was an option I used for the nexusformat package, but I must admit that I'm surprised you didn't find any merge conflicts here.

**Comment by tacaswell** [comment]
I did find conflicts I just fixed them :wink:

**Comment by rayosborn** [comment]
This pull request has been merged and updated in PR #83.

**Pull request closed without merging**
